import sys
import os

if len(sys.argv)<2:
    print("Usage: {} project (to be run from Pipeline)".format(sys.argv[0]))
    sys.exit(0)

project=sys.argv[1]
if project[-1] is not '/':
    project+='/'

print("Project: "+project)
print('mkdir ../'+project)
print('mkdir ../'+project+'Selections')
print('mkdir ../'+project+'Catalogs4LE3')
print('mkdir ../'+project+'GalaxyCatalogs')
print('mkdir ../'+project+'Plots')
print('mkdir ../'+project+'Cls')
print('mkdir ../'+project+'NumberCounts')
print('mkdir ../'+project+'RandomCatalogs')
print('mkdir ../'+project+'2PCF')
print('mkdir ../'+project+'2PCF/Measures')
print('mkdir ../'+project+'2PCF/Params')
print('mkdir ../'+project+'2PCF/Scripts') 
print('mkdir ../'+project+'PK')
print('mkdir ../'+project+'PK/Measures')
print('mkdir ../'+project+'PK/Params')  
print('mkdir ../'+project+'PK/Scripts') 
print('mkdir ../'+project+'CM-2PCF')
print('mkdir ../'+project+'CM-2PCF/Measures')
print('mkdir ../'+project+'CM-2PCF/Params')  
print('mkdir ../'+project+'CM-2PCF/Scripts') 
print('mkdir ../'+project+'CM-PK')
print('mkdir ../'+project+'CM-PK/Measures')
print('mkdir ../'+project+'CM-PK/Params')  
print('mkdir ../'+project+'CM-PK/Scripts') 
print('mkdir ../'+project+'3PCF')
print('mkdir ../'+project+'3PCF/Measures')
print('mkdir ../'+project+'3PCF/Params')  
print('mkdir ../'+project+'3PCF/Scripts') 
print('mkdir ../'+project+'BK')
print('mkdir ../'+project+'BK/Measures')
print('mkdir ../'+project+'BK/Params')  
print('mkdir ../'+project+'BK/Scripts') 
print('cp ../Repo/SelectionInputs/sel_input* ../'+project+'Selections/')

os.mkdir('../'+project)
os.mkdir('../'+project+'Selections')
os.mkdir('../'+project+'Catalogs4LE3')
os.mkdir('../'+project+'GalaxyCatalogs')
os.mkdir('../'+project+'Plots')
os.mkdir('../'+project+'Cls')
os.mkdir('../'+project+'NumberCounts')
os.mkdir('../'+project+'RandomCatalogs')
os.mkdir('../'+project+'2PCF')
os.mkdir('../'+project+'2PCF/Measures')
os.mkdir('../'+project+'2PCF/Params')
os.mkdir('../'+project+'2PCF/Scripts') 
os.mkdir('../'+project+'PK')
os.mkdir('../'+project+'PK/Measures')
os.mkdir('../'+project+'PK/Params')  
os.mkdir('../'+project+'PK/Scripts') 
os.mkdir('../'+project+'CM-2PCF')
os.mkdir('../'+project+'CM-2PCF/Measures')
os.mkdir('../'+project+'CM-2PCF/Params')  
os.mkdir('../'+project+'CM-2PCF/Scripts') 
os.mkdir('../'+project+'CM-PK')
os.mkdir('../'+project+'CM-PK/Measures')
os.mkdir('../'+project+'CM-PK/Params')  
os.mkdir('../'+project+'CM-PK/Scripts') 
os.mkdir('../'+project+'3PCF')
os.mkdir('../'+project+'3PCF/Measures')
os.mkdir('../'+project+'3PCF/Params')  
os.mkdir('../'+project+'3PCF/Scripts') 
os.mkdir('../'+project+'BK')
os.mkdir('../'+project+'BK/Measures')
os.mkdir('../'+project+'BK/Params')  
os.mkdir('../'+project+'BK/Scripts') 

os.system('cp ../Repo/SelectionInputs/sel_input* ../'+project+'Selections/')


